@startuml

abstract class AbstractBiMap extends ForwardingMap implements BiMap, Serializable
abstract class AbstractIndexedListIterator extends UnmodifiableListIterator
abstract class AbstractIterator extends UnmodifiableIterator
abstract class AbstractListMultimap extends AbstractMapBasedMultimap implements ListMultimap
abstract class AbstractMapBasedMultimap extends AbstractMultimap implements Serializable
abstract class AbstractMapBasedMultiset extends AbstractMultiset implements Serializable
abstract class AbstractMapEntry implements Entry
abstract class AbstractMultimap implements Multimap
abstract class AbstractMultiset extends AbstractCollection implements Multiset
abstract class AbstractNavigableMap extends IteratorBasedAbstractMap implements NavigableMap
abstract class AbstractRangeSet implements RangeSet
abstract class AbstractSequentialIterator extends UnmodifiableIterator
abstract class AbstractSetMultimap extends AbstractMapBasedMultimap implements SetMultimap
abstract class AbstractSortedKeySortedSetMultimap extends AbstractSortedSetMultimap
abstract class AbstractSortedMultiset extends AbstractMultiset implements SortedMultiset
abstract class AbstractSortedSetMultimap extends AbstractSetMultimap implements SortedSetMultimap
abstract class AbstractTable implements Table

 class ArrayListMultimap extends ArrayListMultimapGwtSerializationDependencies
abstract class ArrayListMultimapGwtSerializationDependencies extends AbstractListMultimap
 class ArrayTable extends AbstractTable implements Serializable
interface BiMap extends Map
enum BoundType


interface ClassToInstanceMap extends Map

 class Collections2


class CompactHashMap extends AbstractMap implements Serializable
class CompactHashSet extends AbstractSet implements Serializable
class CompactLinkedHashMap extends CompactHashMap
class CompactLinkedHashSet extends CompactHashSet

 class Comparators
abstract class ComparisonChain

class ComputationException extends RuntimeException
 class ConcurrentHashMultiset extends AbstractMultiset implements Serializable
class ConsumingQueueIterator extends AbstractIterator
abstract class ContiguousSet extends ImmutableSortedSet

abstract class Cut implements Comparable, Serializable



abstract class DescendingMultiset extends ForwardingMultiset implements SortedMultiset
abstract class DiscreteDomain

class EmptyImmutableListMultimap extends ImmutableListMultimap
class EmptyImmutableSetMultimap extends ImmutableSetMultimap
 class EnumBiMap
 class EnumHashBiMap extends AbstractBiMap
 class EnumMultiset extends AbstractMultiset implements Serializable
 class EvictingQueue extends ForwardingQueue implements Serializable

class FilteredEntryMultimap extends AbstractMultimap implements FilteredMultimap


class FilteredKeyMultimap extends AbstractMultimap implements FilteredMultimap

interface FilteredMultimap extends Multimap

interface FilteredSetMultimap extends FilteredMultimap, SetMultimap
abstract class FluentIterable implements Iterable
abstract class ForwardingBlockingDeque extends ForwardingDeque implements BlockingDeque
abstract class ForwardingCollection extends ForwardingObject implements Collection
abstract class ForwardingConcurrentMap extends ForwardingMap implements ConcurrentMap
abstract class ForwardingDeque extends ForwardingQueue implements Deque
class ForwardingImmutableCollection
abstract class ForwardingImmutableList
abstract class ForwardingImmutableMap
abstract class ForwardingImmutableSet
abstract class ForwardingIterator extends ForwardingObject implements Iterator
abstract class ForwardingList extends ForwardingCollection implements List
abstract class ForwardingListIterator extends ForwardingIterator implements ListIterator
abstract class ForwardingListMultimap extends ForwardingMultimap implements ListMultimap
abstract class ForwardingMap extends ForwardingObject implements Map
abstract class ForwardingMapEntry extends ForwardingObject implements Map.Entry
abstract class ForwardingMultimap extends ForwardingObject implements Multimap
abstract class ForwardingMultiset extends ForwardingCollection implements Multiset
abstract class ForwardingNavigableMap extends ForwardingSortedMap implements NavigableMap
abstract class ForwardingNavigableSet extends ForwardingSortedSet implements NavigableSet
abstract class ForwardingObject
abstract class ForwardingQueue extends ForwardingCollection implements Queue
abstract class ForwardingSet extends ForwardingCollection implements Set
abstract class ForwardingSetMultimap extends ForwardingMultimap implements SetMultimap
abstract class ForwardingSortedMap extends ForwardingMap implements SortedMap
abstract class ForwardingSortedMultiset extends ForwardingMultiset implements SortedMultiset
abstract class ForwardingSortedSet extends ForwardingSet implements SortedSet
abstract class ForwardingSortedSetMultimap extends ForwardingSetMultimap implements SortedSetMultimap
abstract class ForwardingTable extends ForwardingObject implements Table


class HashBasedTable extends StandardTable
 class HashBiMap extends IteratorBasedAbstractMap implements BiMap, Serializable

 class HashMultimap extends HashMultimapGwtSerializationDependencies
abstract class HashMultimapGwtSerializationDependencies extends AbstractSetMultimap
 class HashMultiset extends AbstractMapBasedMultiset
abstract class ImmutableAsList extends ImmutableList
abstract class ImmutableBiMap extends ImmutableBiMapFauxverideShim implements BiMap
abstract class ImmutableBiMapFauxverideShim extends ImmutableMap
 class ImmutableClassToInstanceMap extends ForwardingMap implements ClassToInstanceMap, Serializable
abstract class ImmutableCollection extends AbstractCollection implements Serializable
class ImmutableEntry extends AbstractMapEntry implements Serializable


abstract class ImmutableList extends ImmutableCollection implements List, RandomAccess
class ImmutableListMultimap extends ImmutableMultimap implements ListMultimap
abstract class ImmutableMap implements Map, Serializable
class ImmutableMapEntry extends ImmutableEntry
abstract class ImmutableMapEntrySet extends ImmutableSet


abstract class ImmutableMultimap extends AbstractMultimap implements Serializable
abstract class ImmutableMultiset extends ImmutableMultisetGwtSerializationDependencies implements Multiset
abstract class ImmutableMultisetGwtSerializationDependencies extends ImmutableCollection
class ImmutableRangeMap implements RangeMap, Serializable
 class ImmutableRangeSet extends AbstractRangeSet implements Serializable
abstract class ImmutableSet extends ImmutableCollection implements Set
class ImmutableSetMultimap extends ImmutableMultimap implements SetMultimap

 class ImmutableSortedMap extends ImmutableSortedMapFauxverideShim implements NavigableMap
abstract class ImmutableSortedMapFauxverideShim extends ImmutableMap
abstract class ImmutableSortedMultiset extends ImmutableSortedMultisetFauxverideShim implements SortedMultiset
abstract class ImmutableSortedMultisetFauxverideShim extends ImmutableMultiset
abstract class ImmutableSortedSet extends ImmutableSortedSetFauxverideShim implements NavigableSet, SortedIterable
abstract class ImmutableSortedSetFauxverideShim extends ImmutableSet
abstract class ImmutableTable extends AbstractTable implements Serializable
interface Interner
 class Interners
 class Iterables
 class Iterators

 class LinkedHashMultimap extends LinkedHashMultimapGwtSerializationDependencies
abstract class LinkedHashMultimapGwtSerializationDependencies extends AbstractSetMultimap
 class LinkedHashMultiset extends AbstractMapBasedMultiset
class LinkedListMultimap extends AbstractMultimap implements ListMultimap, Serializable
interface ListMultimap extends Multimap
 class Lists
interface MapDifference
 class MapMaker
class MapMakerInternalMap< K, V, E extends MapMakerInternalMap.InternalEntry, S extends MapMakerInternalMap.Segment> extends AbstractMap implements ConcurrentMap, Serializable
 class Maps
 class MinMaxPriorityQueue extends AbstractQueue
 class MoreCollectors
interface Multimap
abstract class MultimapBuilder
 class Multimaps
interface Multiset extends Collection
 class Multisets
 class MutableClassToInstanceMap extends ForwardingMap implements ClassToInstanceMap, Serializable



 class ObjectArrays
abstract class Ordering implements Comparator

interface PeekingIterator extends Iterator

 class Queues
 class Range extends RangeGwtSerializationDependencies implements Predicate, Serializable
abstract class RangeGwtSerializationDependencies implements Serializable
interface RangeMap
interface RangeSet

class RegularImmutableAsList extends ImmutableAsList
class RegularImmutableBiMap extends ImmutableBiMap
class RegularImmutableList extends ImmutableList

class RegularImmutableMultiset extends ImmutableMultiset



abstract class RegularImmutableTable extends ImmutableTable


interface RowSortedTable extends Table

interface SetMultimap extends Multimap
 class Sets



class SingletonImmutableTable extends ImmutableTable
interface SortedIterable extends Iterable


interface SortedMapDifference extends MapDifference
interface SortedMultiset extends SortedMultisetBridge, SortedIterable
interface SortedMultisetBridge extends Multiset

interface SortedSetMultimap extends SetMultimap

class StandardRowSortedTable extends StandardTable implements RowSortedTable
class StandardTable extends AbstractTable implements Serializable
 class Streams

interface Table
 class Tables

abstract class TransformedIterator implements Iterator
abstract class TransformedListIterator extends TransformedIterator implements ListIterator
class TreeBasedTable extends StandardRowSortedTable
class TreeMultimap extends AbstractSortedKeySortedSetMultimap
 class TreeMultiset extends AbstractSortedMultiset implements Serializable
 class TreeRangeMap implements RangeMap
class TreeRangeSet extends AbstractRangeSet implements Serializable
abstract class TreeTraverser
abstract class UnmodifiableIterator implements Iterator
abstract class UnmodifiableListIterator extends UnmodifiableIterator implements ListIterator


@enduml