@startuml
 class HostAndPort implements Serializable
 class HostSpecifier
 class HttpHeaders
 class InetAddresses
 class InternetDomainName
 class MediaType

 class PercentEscaper extends UnicodeEscaper
 class UrlEscapers
@enduml