@startuml

abstract class ArrayBasedCharEscaper extends CharEscaper
 class ArrayBasedEscaperMap
abstract class ArrayBasedUnicodeEscaper extends UnicodeEscaper
abstract class CharEscaper extends Escaper
 class CharEscaperBuilder
abstract class Escaper
 class Escapers


abstract class UnicodeEscaper extends Escaper


@enduml