@startuml

abstract class AbstractNestablePropertyAccessor extends AbstractPropertyAccessor
abstract class AbstractPropertyAccessor extends TypeConverterSupport implements ConfigurablePropertyAccessor
abstract class AnnotationBeanUtils

interface BeanInfoFactory
class BeanInstantiationException extends FatalBeanException
class BeanMetadataAttribute implements BeanMetadataElement
class BeanMetadataAttributeAccessor extends AttributeAccessorSupport implements BeanMetadataElement
interface BeanMetadataElement
abstract class BeansException extends NestedRuntimeException
abstract class BeanUtils
interface BeanWrapper extends ConfigurablePropertyAccessor
class BeanWrapperImpl extends AbstractNestablePropertyAccessor implements BeanWrapper
class CachedIntrospectionResults
interface ConfigurablePropertyAccessor extends PropertyAccessor, PropertyEditorRegistry, TypeConverter
class ConversionNotSupportedException extends TypeMismatchException
class DirectFieldAccessor extends AbstractNestablePropertyAccessor
class ExtendedBeanInfo implements BeanInfo
class ExtendedBeanInfoFactory implements BeanInfoFactory, Ordered
interface BeanFactoryLocator
interface BeanFactoryReference
class BootstrapException extends FatalBeanException

class SimpleSpringBeanELResolver extends SpringBeanELResolver
abstract class SpringBeanELResolver extends ELResolver

class SingletonBeanFactoryLocator implements BeanFactoryLocator
interface AnnotatedBeanDefinition extends BeanDefinition
class AnnotatedGenericBeanDefinition extends GenericBeanDefinition implements AnnotatedBeanDefinition
class AnnotationBeanWiringInfoResolver implements BeanWiringInfoResolver
enum Autowire
annotation Autowired
class AutowiredAnnotationBeanPostProcessor extends InstantiationAwareBeanPostProcessorAdapter implements MergedBeanDefinitionPostProcessor, PriorityOrdered, BeanFactoryAware
class BeanFactoryAnnotationUtils
annotation Configurable
class CustomAutowireConfigurer implements BeanFactoryPostProcessor, BeanClassLoaderAware, Ordered
class InitDestroyAnnotationBeanPostProcessor implements DestructionAwareBeanPostProcessor, MergedBeanDefinitionPostProcessor, PriorityOrdered, Serializable
class InjectionMetadata
annotation Lookup

annotation Qualifier
class QualifierAnnotationAutowireCandidateResolver extends GenericTypeAwareAutowireCandidateResolver
annotation Required
class RequiredAnnotationBeanPostProcessor extends InstantiationAwareBeanPostProcessorAdapter implements MergedBeanDefinitionPostProcessor, PriorityOrdered, BeanFactoryAware
annotation Value
interface Aware
interface BeanClassLoaderAware extends Aware
class BeanCreationException extends FatalBeanException
class BeanCreationNotAllowedException extends BeanCreationException
class BeanCurrentlyInCreationException extends BeanCreationException
class BeanDefinitionStoreException extends FatalBeanException
class BeanExpressionException extends FatalBeanException
interface BeanFactory
interface BeanFactoryAware extends Aware
abstract class BeanFactoryUtils
class BeanInitializationException extends FatalBeanException
class BeanIsAbstractException extends BeanCreationException
class BeanIsNotAFactoryException extends BeanNotOfRequiredTypeException
interface BeanNameAware extends Aware
class BeanNotOfRequiredTypeException extends BeansException
class CannotLoadBeanClassException extends FatalBeanException
abstract class AbstractFactoryBean implements FactoryBean, BeanClassLoaderAware, BeanFactoryAware, InitializingBean, DisposableBean
interface AutowireCapableBeanFactory extends BeanFactory
interface BeanDefinition extends AttributeAccessor, BeanMetadataElement
class BeanDefinitionHolder implements BeanMetadataElement
class BeanDefinitionVisitor
class BeanExpressionContext
interface BeanExpressionResolver
interface BeanFactoryPostProcessor
interface BeanPostProcessor
interface BeanReference extends BeanMetadataElement
interface ConfigurableBeanFactory extends HierarchicalBeanFactory, SingletonBeanRegistry
interface ConfigurableListableBeanFactory extends ListableBeanFactory, AutowireCapableBeanFactory, ConfigurableBeanFactory
class ConstructorArgumentValues
class CustomEditorConfigurer implements BeanFactoryPostProcessor, Ordered
class CustomScopeConfigurer implements BeanFactoryPostProcessor, BeanClassLoaderAware, Ordered
class DependencyDescriptor implements Serializable
class DeprecatedBeanWarner implements BeanFactoryPostProcessor
interface DestructionAwareBeanPostProcessor extends BeanPostProcessor
class FieldRetrievingFactoryBean implements FactoryBean, BeanNameAware, BeanClassLoaderAware, InitializingBean
interface InstantiationAwareBeanPostProcessor extends BeanPostProcessor
abstract class InstantiationAwareBeanPostProcessorAdapter implements SmartInstantiationAwareBeanPostProcessor
class ListFactoryBean extends AbstractFactoryBean
class MapFactoryBean extends AbstractFactoryBean
class MethodInvokingBean extends ArgumentConvertingMethodInvoker implements BeanClassLoaderAware, BeanFactoryAware, InitializingBean
class MethodInvokingFactoryBean extends MethodInvokingBean implements FactoryBean
class ObjectFactoryCreatingFactoryBean extends AbstractFactoryBean

abstract class PlaceholderConfigurerSupport extends PropertyResourceConfigurer implements BeanNameAware, BeanFactoryAware
class PreferencesPlaceholderConfigurer extends PropertyPlaceholderConfigurer implements InitializingBean
class PropertiesFactoryBean extends PropertiesLoaderSupport implements FactoryBean, InitializingBean
class PropertyOverrideConfigurer extends PropertyResourceConfigurer
class PropertyPathFactoryBean implements FactoryBean, BeanNameAware, BeanFactoryAware
class PropertyPlaceholderConfigurer extends PlaceholderConfigurerSupport
abstract class PropertyResourceConfigurer extends PropertiesLoaderSupport implements BeanFactoryPostProcessor, PriorityOrdered
class ProviderCreatingFactoryBean extends AbstractFactoryBean
class RuntimeBeanNameReference implements BeanReference
class RuntimeBeanReference implements BeanReference
interface Scope
class ServiceLocatorFactoryBean implements FactoryBean, BeanFactoryAware, InitializingBean
class SetFactoryBean extends AbstractFactoryBean
interface SingletonBeanRegistry
interface SmartInstantiationAwareBeanPostProcessor extends InstantiationAwareBeanPostProcessor
class TypedStringValue implements BeanMetadataElement
class YamlMapFactoryBean extends YamlProcessor implements FactoryBean, InitializingBean
abstract class YamlProcessor
class YamlPropertiesFactoryBean extends YamlProcessor implements FactoryBean, InitializingBean
interface DisposableBean
interface FactoryBean
class FactoryBeanNotInitializedException extends FatalBeanException
interface HierarchicalBeanFactory extends BeanFactory
interface InitializingBean
interface ListableBeanFactory extends BeanFactory
interface NamedBean
class NoSuchBeanDefinitionException extends BeansException
class NoUniqueBeanDefinitionException extends NoSuchBeanDefinitionException
interface ObjectFactory

abstract class AbstractComponentDefinition implements ComponentDefinition
class AliasDefinition implements BeanMetadataElement
class BeanComponentDefinition extends BeanDefinitionHolder implements ComponentDefinition
class BeanDefinitionParsingException extends BeanDefinitionStoreException
class BeanEntry implements ParseState.Entry
interface ComponentDefinition extends BeanMetadataElement
class CompositeComponentDefinition extends AbstractComponentDefinition
class ConstructorArgumentEntry implements ParseState.Entry
interface DefaultsDefinition extends BeanMetadataElement
class EmptyReaderEventListener implements ReaderEventListener
class FailFastProblemReporter implements ProblemReporter
class ImportDefinition implements BeanMetadataElement
class Location
class NullSourceExtractor implements SourceExtractor

 class ParseState
class PassThroughSourceExtractor implements SourceExtractor
class Problem
interface ProblemReporter
class PropertyEntry implements ParseState.Entry
class QualifierEntry implements ParseState.Entry
class ReaderContext
interface ReaderEventListener extends EventListener
interface SourceExtractor
abstract class AbstractServiceLoaderBasedFactoryBean extends AbstractFactoryBean implements BeanClassLoaderAware

class ServiceFactoryBean extends AbstractServiceLoaderBasedFactoryBean implements BeanClassLoaderAware
class ServiceListFactoryBean extends AbstractServiceLoaderBasedFactoryBean implements BeanClassLoaderAware
class ServiceLoaderFactoryBean extends AbstractServiceLoaderBasedFactoryBean implements BeanClassLoaderAware
interface SmartFactoryBean extends FactoryBean
interface SmartInitializingSingleton
abstract class AbstractAutowireCapableBeanFactory extends AbstractBeanFactory implements AutowireCapableBeanFactory
abstract class AbstractBeanDefinition extends BeanMetadataAttributeAccessor implements BeanDefinition, Cloneable
abstract class AbstractBeanDefinitionReader implements EnvironmentCapable, BeanDefinitionReader
abstract class AbstractBeanFactory extends FactoryBeanRegistrySupport implements ConfigurableBeanFactory
class AutowireCandidateQualifier extends BeanMetadataAttributeAccessor
interface AutowireCandidateResolver
abstract class AutowireUtils
class BeanDefinitionBuilder
class BeanDefinitionDefaults
interface BeanDefinitionReader
class BeanDefinitionReaderUtils
interface BeanDefinitionRegistry extends AliasRegistry
interface BeanDefinitionRegistryPostProcessor extends BeanFactoryPostProcessor
class BeanDefinitionResource extends AbstractResource
class BeanDefinitionValidationException extends FatalBeanException
class BeanDefinitionValueResolver
interface BeanNameGenerator
class CglibSubclassingInstantiationStrategy extends SimpleInstantiationStrategy
class ChildBeanDefinition extends AbstractBeanDefinition
class ConstructorResolver
class DefaultBeanNameGenerator implements BeanNameGenerator
class DefaultListableBeanFactory extends AbstractAutowireCapableBeanFactory implements ConfigurableListableBeanFactory, BeanDefinitionRegistry, Serializable
class DefaultSingletonBeanRegistry extends SimpleAliasRegistry implements SingletonBeanRegistry
class DisposableBeanAdapter implements DisposableBean, Runnable, Serializable
abstract class FactoryBeanRegistrySupport extends DefaultSingletonBeanRegistry
class GenericBeanDefinition extends AbstractBeanDefinition
class GenericTypeAwareAutowireCandidateResolver implements AutowireCandidateResolver, BeanFactoryAware
interface InstantiationStrategy
class LookupOverride extends MethodOverride
class ManagedArray extends ManagedList
class ManagedList extends ArrayList implements Mergeable, BeanMetadataElement
class ManagedMap extends LinkedHashMap implements Mergeable, BeanMetadataElement
class ManagedProperties extends Properties implements Mergeable, BeanMetadataElement
class ManagedSet extends LinkedHashSet implements Mergeable, BeanMetadataElement
interface MergedBeanDefinitionPostProcessor extends BeanPostProcessor
abstract class MethodOverride implements BeanMetadataElement
class MethodOverrides
interface MethodReplacer

class PropertiesBeanDefinitionReader extends AbstractBeanDefinitionReader
class ReplaceOverride extends MethodOverride
class RootBeanDefinition extends AbstractBeanDefinition
interface SecurityContextProvider
class SimpleAutowireCandidateResolver implements AutowireCandidateResolver
class SimpleBeanDefinitionRegistry extends SimpleAliasRegistry implements BeanDefinitionRegistry
class SimpleInstantiationStrategy implements InstantiationStrategy
class SimpleSecurityContextProvider implements SecurityContextProvider
class StaticListableBeanFactory implements ListableBeanFactory
class UnsatisfiedDependencyException extends BeanCreationException
class BeanConfigurerSupport implements BeanFactoryAware, InitializingBean, DisposableBean
class BeanWiringInfo
interface BeanWiringInfoResolver
class ClassNameBeanWiringInfoResolver implements BeanWiringInfoResolver

abstract class AbstractBeanDefinitionParser implements BeanDefinitionParser
abstract class AbstractSimpleBeanDefinitionParser extends AbstractSingleBeanDefinitionParser
abstract class AbstractSingleBeanDefinitionParser extends AbstractBeanDefinitionParser
interface BeanDefinitionDecorator
interface BeanDefinitionDocumentReader
interface BeanDefinitionParser
class BeanDefinitionParserDelegate
class BeansDtdResolver implements EntityResolver
class DefaultBeanDefinitionDocumentReader implements BeanDefinitionDocumentReader
class DefaultDocumentLoader implements DocumentLoader
class DefaultNamespaceHandlerResolver implements NamespaceHandlerResolver
class DelegatingEntityResolver implements EntityResolver
class DocumentDefaultsDefinition implements DefaultsDefinition
interface DocumentLoader
interface NamespaceHandler
interface NamespaceHandlerResolver
abstract class NamespaceHandlerSupport implements NamespaceHandler

 class ParserContext
class PluggableSchemaResolver implements EntityResolver
class ResourceEntityResolver extends DelegatingEntityResolver
class SimpleConstructorNamespaceHandler implements NamespaceHandler
class SimplePropertyNamespaceHandler implements NamespaceHandler
class UtilNamespaceHandler extends NamespaceHandlerSupport
class XmlBeanDefinitionReader extends AbstractBeanDefinitionReader
class XmlBeanDefinitionStoreException extends BeanDefinitionStoreException
class XmlBeanFactory extends DefaultListableBeanFactory
class XmlReaderContext extends ReaderContext
class FatalBeanException extends BeansException

class InvalidPropertyException extends FatalBeanException
interface Mergeable
class MethodInvocationException extends PropertyAccessException
class MutablePropertyValues implements PropertyValues, Serializable
class NotReadablePropertyException extends InvalidPropertyException
class NotWritablePropertyException extends InvalidPropertyException
class NullValueInNestedPathException extends InvalidPropertyException

abstract class PropertyAccessException extends BeansException implements ErrorCoded
interface PropertyAccessor
abstract class PropertyAccessorFactory
abstract class PropertyAccessorUtils
class PropertyBatchUpdateException extends BeansException
class PropertyDescriptorUtils
interface PropertyEditorRegistrar
interface PropertyEditorRegistry
class PropertyEditorRegistrySupport implements PropertyEditorRegistry
class ByteArrayPropertyEditor extends PropertyEditorSupport
class CharacterEditor extends PropertyEditorSupport
class CharArrayPropertyEditor extends PropertyEditorSupport
class CharsetEditor extends PropertyEditorSupport
class ClassArrayEditor extends PropertyEditorSupport
class ClassEditor extends PropertyEditorSupport
class CurrencyEditor extends PropertyEditorSupport
class CustomBooleanEditor extends PropertyEditorSupport
class CustomCollectionEditor extends PropertyEditorSupport
class CustomDateEditor extends PropertyEditorSupport
class CustomMapEditor extends PropertyEditorSupport
class CustomNumberEditor extends PropertyEditorSupport
class FileEditor extends PropertyEditorSupport
class InputSourceEditor extends PropertyEditorSupport
class InputStreamEditor extends PropertyEditorSupport
class LocaleEditor extends PropertyEditorSupport

class PatternEditor extends PropertyEditorSupport
class PropertiesEditor extends PropertyEditorSupport
class ReaderEditor extends PropertyEditorSupport
class ResourceBundleEditor extends PropertyEditorSupport
class StringArrayPropertyEditor extends PropertyEditorSupport
class StringTrimmerEditor extends PropertyEditorSupport
class TimeZoneEditor extends PropertyEditorSupport
class URIEditor extends PropertyEditorSupport
class URLEditor extends PropertyEditorSupport
class UUIDEditor extends PropertyEditorSupport
class ZoneIdEditor extends PropertyEditorSupport
abstract class PropertyMatches
class PropertyValue extends BeanMetadataAttributeAccessor implements Serializable
interface PropertyValues
class PropertyValuesEditor extends PropertyEditorSupport
class SimpleTypeConverter extends TypeConverterSupport
class ArgumentConvertingMethodInvoker extends MethodInvoker
class MutableSortDefinition implements SortDefinition, Serializable

class PagedListHolder implements Serializable
class PropertyComparator implements Comparator
class ResourceEditorRegistrar implements PropertyEditorRegistrar
interface SortDefinition
interface TypeConverter
class TypeConverterDelegate
abstract class TypeConverterSupport extends PropertyEditorRegistrySupport implements TypeConverter
class TypeMismatchException extends PropertyAccessException


@enduml