@startuml

component [Slf4j-api] as api
component [Slf4j-nop] as nop
component [Slf4j-simple] as simple
component [Slf4j-log4j12] as log4j12
component [Slf4j-jdk14] as jdk14
component [Slf4j-jcl] as jcl

api --> StaticLoggerBinder

StaticLoggerBinder --> nop
StaticLoggerBinder --> simple
StaticLoggerBinder --> log4j12
StaticLoggerBinder --> jdk14
StaticLoggerBinder --> jcl

LoggerFactoryBinder <|-- StaticLoggerBinder
LoggerFactoryBinder -- getLoggerFactory
getLoggerFactory -- getLogger

@enduml