@startuml

class AbandonedTrace implements TrackedUse
class BasicDataSource implements DataSource, BasicDataSourceMXBean, MBeanRegistration, AutoCloseable
class BasicDataSourceFactory implements ObjectFactory
interface BasicDataSourceMXBean
interface ConnectionFactory
class Constants
class ConnectionImpl extends DelegatingConnection
class DriverAdapterCPDS implements ConnectionPoolDataSource, Referenceable, Serializable, ObjectFactory

class PooledConnectionImpl implements PooledConnection, KeyedPooledObjectFactory
class PStmtKeyCPDS extends PStmtKey
class DataSourceConnectionFactory implements ConnectionFactory
class CPDSConnectionFactory implements PooledObjectFactory, ConnectionEventListener, PooledConnectionManager
abstract class InstanceKeyDataSource implements DataSource, Referenceable, Serializable, AutoCloseable
abstract class InstanceKeyDataSourceFactory implements ObjectFactory
class KeyedCPDSConnectionFactory implements KeyedPooledObjectFactory, ConnectionEventListener, PooledConnectionManager

class PerUserPoolDataSource extends InstanceKeyDataSource
class PerUserPoolDataSourceFactory extends InstanceKeyDataSourceFactory

interface PooledConnectionManager
class PoolKey implements Serializable
class SharedPoolDataSource extends InstanceKeyDataSource
class SharedPoolDataSourceFactory extends InstanceKeyDataSourceFactory
class UserPassKey implements Serializable
class DelegatingCallableStatement extends DelegatingPreparedStatement implements CallableStatement
class DelegatingConnection<C extends Connection> extends AbandonedTrace implements Connection
class DelegatingDatabaseMetaData implements DatabaseMetaData
class DelegatingPreparedStatement extends DelegatingStatement implements PreparedStatement
 class DelegatingResultSet extends AbandonedTrace implements ResultSet
class DelegatingStatement extends AbandonedTrace implements Statement
class DriverConnectionFactory implements ConnectionFactory
class DriverManagerConnectionFactory implements ConnectionFactory

class BasicManagedDataSource extends BasicDataSource
class DataSourceXAConnectionFactory implements XAConnectionFactory
class LocalXAConnectionFactory implements XAConnectionFactory
class ManagedConnection<C extends Connection> extends DelegatingConnection
class ManagedDataSource<C extends Connection> extends PoolingDataSource

class PoolableManagedConnection extends PoolableConnection
class PoolableManagedConnectionFactory extends PoolableConnectionFactory
class TransactionContext
interface TransactionContextListener
class TransactionRegistry
interface XAConnectionFactory extends ConnectionFactory

class PoolableCallableStatement extends DelegatingCallableStatement
class PoolableConnection extends DelegatingConnection implements PoolableConnectionMXBean
class PoolableConnectionFactory implements PooledObjectFactory
interface PoolableConnectionMXBean
class PoolablePreparedStatement extends DelegatingPreparedStatement
class PoolingConnection extends DelegatingConnection implements KeyedPooledObjectFactory
class PoolingDataSource<C extends Connection> implements DataSource, AutoCloseable
class PoolingDriver implements Driver
class PStmtKey
class SwallowedExceptionLogger implements SwallowedExceptionListener
 class Utils


@enduml