@startuml

annotation Generated
annotation ManagedBean
annotation PostConstruct
annotation PreDestroy
annotation Resource
annotation Resources
annotation DeclareRoles
annotation DenyAll
annotation PermitAll
annotation RolesAllowed
annotation RunAs
annotation DataSourceDefinition
annotation DataSourceDefinitions
annotation EJB
annotation EJBs
class ArrayELResolver extends ELResolver
class BeanELResolver extends ELResolver
class CompositeELResolver extends ELResolver
abstract class ELContext
class ELContextEvent extends EventObject
interface ELContextListener extends java.util.EventListener
class ELException extends RuntimeException
abstract class ELResolver
abstract class Expression implements Serializable
abstract class ExpressionFactory
abstract class FunctionMapper
class ListELResolver extends ELResolver
class MapELResolver extends ELResolver
abstract class MethodExpression extends Expression
class MethodInfo
class MethodNotFoundException extends ELException
class PropertyNotFoundException extends ELException
class PropertyNotWritableException extends ELException
class ResourceBundleELResolver extends ELResolver
class Util
abstract class ValueExpression extends Expression
class ValueReference implements Serializable
abstract class VariableMapper
class Authenticator
class InternetAddress
class MimeMessage implements MimePart
interface MimePart
class MimePartDataSource
class PasswordAuthentication
class Session
annotation PersistenceContext
annotation PersistenceContexts
enum PersistenceContextType
annotation PersistenceProperty
annotation PersistenceUnit
annotation PersistenceUnits
annotation HandlesTypes
annotation HttpConstraint
annotation HttpMethodConstraint
annotation MultipartConfig
annotation ServletSecurity
annotation WebFilter
annotation WebInitParam
annotation WebListener
annotation WebServlet
interface AsyncContext
class AsyncEvent
interface AsyncListener extends EventListener
interface JspConfigDescriptor
interface JspPropertyGroupDescriptor
interface TaglibDescriptor
enum DispatcherType
interface Filter
interface FilterChain
interface FilterConfig
interface FilterRegistration extends Registration
abstract class GenericServlet implements Servlet, ServletConfig, java.io.Serializable
class Cookie implements Cloneable, Serializable
abstract class HttpServlet extends GenericServlet
interface HttpServletRequest extends ServletRequest
class HttpServletRequestWrapper extends ServletRequestWrapper implements HttpServletRequest
interface HttpServletResponse extends ServletResponse
class HttpServletResponseWrapper extends ServletResponseWrapper implements HttpServletResponse
interface HttpSession
interface HttpSessionActivationListener extends EventListener
interface HttpSessionAttributeListener extends EventListener
class HttpSessionBindingEvent extends HttpSessionEvent
interface HttpSessionBindingListener extends EventListener
interface HttpSessionContext
class HttpSessionEvent extends java.util.EventObject
interface HttpSessionListener extends EventListener
class HttpUtils
interface Part
class HttpConstraintElement
class HttpMethodConstraintElement extends HttpConstraintElement
class ELException extends Exception
class ELParseException extends ELException
abstract class Expression
abstract class ExpressionEvaluator
interface FunctionMapper
class ImplicitObjectELResolver extends ELResolver
class ScopedAttributeELResolver extends ELResolver
interface VariableResolver
 class ErrorData
interface HttpJspPage extends JspPage
interface JspApplicationContext
abstract class JspContext
abstract class JspEngineInfo
class JspException extends Exception
abstract class JspFactory
interface JspPage extends Servlet
class JspTagException extends JspException
abstract class JspWriter extends java.io.Writer
abstract class PageContext extends JspContext
class SkipPageException extends JspException
abstract class BodyContent extends JspWriter
interface BodyTag extends IterationTag
class BodyTagSupport extends TagSupport implements BodyTag
interface DynamicAttributes
class FunctionInfo
interface IterationTag extends Tag
abstract class JspFragment
interface JspIdConsumer
interface JspTag
abstract class PageData
interface SimpleTag extends JspTag
class SimpleTagSupport implements SimpleTag
interface Tag extends JspTag
class TagAdapter implements Tag
class TagAttributeInfo
class TagData implements Cloneable
abstract class TagExtraInfo
class TagFileInfo
class TagInfo
abstract class TagLibraryInfo
abstract class TagLibraryValidator
class TagSupport implements IterationTag, Serializable
class TagVariableInfo
interface TryCatchFinally
class ValidationMessage
class VariableInfo
class MultipartConfigElement
interface Registration
interface RequestDispatcher
interface Servlet
interface ServletConfig
interface ServletContainerInitializer
interface ServletContext
class ServletContextAttributeEvent extends ServletContextEvent
interface ServletContextAttributeListener extends EventListener
class ServletContextEvent extends java.util.EventObject
interface ServletContextListener extends EventListener
class ServletException extends Exception
abstract class ServletInputStream extends InputStream
abstract class ServletOutputStream extends OutputStream
interface ServletRegistration extends Registration
interface ServletRequest
class ServletRequestAttributeEvent extends ServletRequestEvent
interface ServletRequestAttributeListener extends EventListener
class ServletRequestEvent extends java.util.EventObject
interface ServletRequestListener extends EventListener
class ServletRequestWrapper implements ServletRequest
interface ServletResponse
class ServletResponseWrapper implements ServletResponse
class ServletSecurityElement extends HttpConstraintElement
interface SessionCookieConfig
enum SessionTrackingMode
interface SingleThreadModel
class UnavailableException extends ServletException
annotation ClientEndpoint
interface ClientEndpointConfig extends EndpointConfig
class CloseReason
abstract class ContainerProvider
class DecodeException extends Exception
interface Decoder

class DeploymentException extends Exception
class EncodeException extends Exception
interface Encoder
abstract class Endpoint
interface EndpointConfig
interface Extension
interface HandshakeResponse
interface MessageHandler
annotation OnClose
annotation OnError
annotation OnMessage
annotation OnOpen
interface PongMessage
interface RemoteEndpoint
interface SendHandler
 class SendResult

interface HandshakeRequest
annotation PathParam
interface ServerApplicationConfig
interface ServerContainer extends WebSocketContainer
annotation ServerEndpoint
interface ServerEndpointConfig extends EndpointConfig
interface Session extends Closeable
class SessionException extends Exception
interface WebSocketContainer
annotation WebServiceRef
annotation WebServiceRefs
interface AccessLog
abstract class AbstractCatalinaCommandTask extends AbstractCatalinaTask
abstract class AbstractCatalinaTask extends BaseRedirectorHelperTask
abstract class BaseRedirectorHelperTask extends Task
class DeployTask extends AbstractCatalinaCommandTask
class FindLeaksTask extends AbstractCatalinaTask
class JKStatusUpdateTask extends AbstractCatalinaTask
class Arg
class JMXAccessorCondition extends ProjectComponent implements Condition
class JMXAccessorCreateTask extends JMXAccessorTask
class JMXAccessorEqualsCondition  extends ProjectComponent  implements Condition
class JMXAccessorGetTask extends JMXAccessorTask
class JMXAccessorInvokeTask extends JMXAccessorTask
class JMXAccessorQueryTask extends JMXAccessorTask
class JMXAccessorSetTask extends JMXAccessorTask
class JMXAccessorTask extends BaseRedirectorHelperTask
class JMXAccessorUnregisterTask extends JMXAccessorTask
class JMXGetTask extends AbstractCatalinaTask
class JMXQueryTask extends AbstractCatalinaTask
class JMXSetTask extends AbstractCatalinaTask
class ListTask extends AbstractCatalinaTask
class ReloadTask extends AbstractCatalinaCommandTask
class ResourcesTask extends AbstractCatalinaTask
class ServerinfoTask extends AbstractCatalinaTask
class SessionsTask extends AbstractCatalinaCommandTask
class StartTask extends AbstractCatalinaCommandTask
class StopTask extends AbstractCatalinaCommandTask
class ThreaddumpTask extends AbstractCatalinaTask
class UndeployTask extends AbstractCatalinaCommandTask
class ValidatorTask extends BaseRedirectorHelperTask
class VminfoTask extends AbstractCatalinaTask
interface AsyncDispatcher
abstract class AuthenticatorBase extends ValveBase implements Authenticator
class BasicAuthenticator extends AuthenticatorBase
class Constants
class DigestAuthenticator extends AuthenticatorBase
class FormAuthenticator extends AuthenticatorBase
 class NonLoginAuthenticator extends AuthenticatorBase
 class SavedRequest
class SingleSignOn extends ValveBase
class SingleSignOnEntry implements Serializable
class SingleSignOnListener implements SessionListener, Serializable
class SingleSignOnSessionKey implements Serializable
class SpnegoAuthenticator extends AuthenticatorBase
class SSLAuthenticator extends AuthenticatorBase
interface Authenticator
class CatalinaFactory
interface Cluster
interface CometEvent
interface CometFilter extends Filter
interface CometFilterChain
interface CometProcessor extends Servlet
 class ClientAbortException extends IOException
class CometEventImpl implements CometEvent
class Connector extends LifecycleMBeanBase
 class Constants
class CoyoteAdapter implements Adapter
class CoyoteInputStream extends ServletInputStream
class CoyoteOutputStream extends ServletOutputStream
class CoyotePrincipal implements Principal, Serializable
class CoyoteReader extends BufferedReader
class CoyoteWriter extends PrintWriter
class InputBuffer extends Reader implements ByteChunk.ByteInputChannel, CharChunk.CharInputChannel, CharChunk.CharOutputChannel
class MapperListener extends LifecycleMBeanBase implements ContainerListener, LifecycleListener
class OutputBuffer extends Writer implements ByteChunk.ByteOutputChannel, CharChunk.CharOutputChannel
class Request implements HttpServletRequest
class RequestFacade implements HttpServletRequest
class Response implements HttpServletResponse
class ResponseFacade implements HttpServletResponse
interface Contained
interface Container extends Lifecycle
 class ContainerEvent extends EventObject
interface ContainerListener
interface ContainerServlet
interface Context extends Container
class AccessLogAdapter implements AccessLog
class ApplicationContext implements ServletContext
class ApplicationContextFacade implements ServletContext


 class ApplicationFilterConfig implements FilterConfig, Serializable
 class ApplicationFilterFactory
class ApplicationFilterRegistration implements FilterRegistration.Dynamic
class ApplicationHttpRequest extends HttpServletRequestWrapper
class ApplicationHttpResponse extends HttpServletResponseWrapper
class ApplicationJspConfigDescriptor implements JspConfigDescriptor
class ApplicationJspPropertyGroupDescriptor implements JspPropertyGroupDescriptor
class ApplicationPart implements Part
class ApplicationRequest extends ServletRequestWrapper
class ApplicationResponse extends ServletResponseWrapper
class ApplicationServletRegistration implements ServletRegistration.Dynamic
class ApplicationSessionCookieConfig implements SessionCookieConfig
class ApplicationTaglibDescriptor implements TaglibDescriptor
class AprLifecycleListener implements LifecycleListener
class AsyncContextImpl implements AsyncContext, AsyncContextCallback
class AsyncListenerWrapper
class Constants
abstract class ContainerBase extends LifecycleMBeanBase implements Container
class DefaultInstanceManager implements InstanceManager
class JasperListener implements LifecycleListener
class JreMemoryLeakPreventionListener implements LifecycleListener
class NamingContextListener implements LifecycleListener, ContainerListener, PropertyChangeListener
class StandardContext extends ContainerBase implements Context, NotificationEmitter

class StandardEngine extends ContainerBase implements Engine

class StandardHost extends ContainerBase implements Host

class StandardPipeline extends LifecycleBase implements Pipeline, Contained
 class StandardServer extends LifecycleMBeanBase implements Server
class StandardService extends LifecycleMBeanBase implements Service
class StandardThreadExecutor extends LifecycleMBeanBase implements Executor, ResizableExecutor
class StandardWrapper extends ContainerBase implements ServletConfig, Wrapper, NotificationEmitter
 class StandardWrapperFacade implements ServletConfig

class ThreadLocalLeakPreventionListener implements LifecycleListener, ContainerListener
class ApplicationListener
class ApplicationParameter implements Serializable
class Constants
class ContextEjb extends ResourceBase
class ContextEnvironment extends ResourceBase
class ContextHandler extends ResourceBase
class ContextLocalEjb extends ResourceBase
class ContextResource extends ResourceBase
class ContextResourceEnvRef extends ResourceBase
class ContextResourceLink extends ResourceBase
class ContextService extends ResourceBase
class ContextTransaction implements Serializable
class ErrorPage implements Serializable
class FilterDef implements Serializable
class FilterMap implements Serializable
interface Injectable
class InjectionTarget implements Serializable
class JspPropertyGroup
class LoginConfig implements Serializable
class MessageDestination extends ResourceBase
class MessageDestinationRef extends ResourceBase
class MultipartDef implements Serializable
class NamingResources extends LifecycleMBeanBase implements Serializable
class ResourceBase implements Serializable, Injectable
class SecurityCollection implements Serializable
class SecurityConstraint implements Serializable
class SecurityRoleRef implements Serializable
class ServletDef implements Serializable
class SessionConfig
class WebXml
interface DistributedManager
interface Engine extends Container
interface Executor extends java.util.concurrent.Executor, Lifecycle
class AddDefaultCharsetFilter extends FilterBase
 class Constants
class CorsFilter implements Filter
class CsrfPreventionFilter extends CsrfPreventionFilterBase
abstract class CsrfPreventionFilterBase extends FilterBase
class ExpiresFilter extends FilterBase
class FailedRequestFilter extends FilterBase implements CometFilter
abstract class FilterBase implements Filter
class HttpHeaderSecurityFilter extends FilterBase
 class RemoteAddrFilter extends RequestFilter
 class RemoteHostFilter extends RequestFilter
class RemoteIpFilter implements Filter
class RequestDumperFilter implements Filter
abstract class RequestFilter extends FilterBase implements CometFilter
class RestCsrfPreventionFilter extends CsrfPreventionFilterBase
class SetCharacterEncodingFilter extends FilterBase
class WebdavFixFilter implements Filter
 class Globals
interface Group extends Principal
class ClusterSingleSignOn extends SingleSignOn implements ClusterValve, MapOwner
class ClusterSingleSignOnListener extends SingleSignOnListener implements ReplicatedSessionListener
class CollectedInfo
class HeartbeatListener implements LifecycleListener, ContainerListener
class MultiCastSender implements Sender
class Proxy
interface Sender
class TcpSender implements Sender
interface CatalinaCluster extends Cluster
interface ClusterDeployer extends ChannelListener
abstract class ClusterListener implements ChannelListener
interface ClusterManager extends Manager
interface ClusterMessage extends Serializable
class ClusterMessageBase implements ClusterMessage
class ClusterRuleSet extends RuleSetBase
interface ClusterSession extends Session, HttpSession
interface ClusterValve extends Valve
class ReplicatedContext extends StandardContext implements MapOwner
class Constants
class FarmWarDeployer extends ClusterListener implements ClusterDeployer, FileChangeListener
interface FileChangeListener
class FileMessage extends ClusterMessageBase
class FileMessageFactory
class UndeployMessage implements ClusterMessage
class WarWatcher
class ClusterJmxHelper
class BackupManager extends ClusterManagerBase implements MapOwner, DistributedManager
abstract class ClusterManagerBase extends ManagerBase implements ClusterManager
class ClusterSessionListener extends ClusterListener
class Constants
class DeltaManager extends ClusterManagerBase
class DeltaRequest implements Externalizable
class DeltaSession extends StandardSession implements Externalizable,ClusterSession,ReplicatedMapEntry
class JvmRouteBinderValve extends ValveBase implements ClusterValve
class JvmRouteSessionIDBinderListener extends ClusterListener
interface ReplicatedSessionListener extends SessionListener, Serializable
class SerializablePrincipal  implements java.io.Serializable
class SessionIDMessage extends ClusterMessageBase
interface SessionMessage extends ClusterMessage
class SessionMessageImpl extends ClusterMessageBase implements SessionMessage
class Constants
class ReplicationValve extends ValveBase implements ClusterValve
class SendMessageData
class SimpleTcpCluster extends LifecycleMBeanBase implements CatalinaCluster, LifecycleListener, IDynamicProperty, MembershipListener, ChannelListener
interface IDynamicProperty
interface Host extends Container
 class InstanceEvent extends EventObject
interface InstanceListener
interface Lifecycle
 class LifecycleEvent extends EventObject
 class LifecycleException extends Exception
interface LifecycleListener
enum LifecycleState
class Constants
class JdbcLeakPrevention
class ParallelWebappClassLoader extends WebappClassLoaderBase
class ResourceEntry
class StandardClassLoader extends URLClassLoader implements StandardClassLoaderMBean
interface StandardClassLoaderMBean
class VirtualWebappLoader extends WebappLoader
class WebappClassLoader extends WebappClassLoaderBase
abstract class WebappClassLoaderBase extends URLClassLoader implements Lifecycle, InstrumentableClassLoader, PermissionCheck
class WebappLoader extends LifecycleMBeanBase implements Loader, PropertyChangeListener
interface Loader
class Constants
class DummyProxySession implements Session
class Constants
class HostManagerServlet extends HttpServlet implements ContainerServlet
 class HTMLHostManagerServlet extends HostManagerServlet
 class HTMLManagerServlet extends ManagerServlet
class JMXProxyServlet extends HttpServlet
class JspHelper
class ManagerServlet extends HttpServlet implements ContainerServlet
class StatusManagerServlet extends HttpServlet implements NotificationListener
class StatusTransformer
abstract class BaseSessionComparator implements Comparator
class SessionUtils
interface Manager
class ClassNameMBean extends BaseModelMBean
class ConnectorMBean extends ClassNameMBean
class Constants
class ContainerMBean extends BaseModelMBean
class ContextEnvironmentMBean extends BaseModelMBean
class ContextMBean extends ContainerMBean
class ContextResourceLinkMBean extends BaseModelMBean
class ContextResourceMBean extends BaseModelMBean
class GlobalResourcesLifecycleListener implements LifecycleListener
class GroupMBean extends BaseModelMBean
class JmxRemoteLifecycleListener implements LifecycleListener
class MBeanDumper
class MBeanFactory
class MBeanUtils
class MemoryUserDatabaseMBean extends BaseModelMBean
class NamingResourcesMBean extends BaseModelMBean
class RoleMBean extends BaseModelMBean
class ServiceMBean extends BaseModelMBean
class UserMBean extends BaseModelMBean
interface Pipeline
class CombinedRealm extends RealmBase
 class Constants
class DataSourceRealm extends RealmBase
class GenericPrincipal implements Principal
class JAASCallbackHandler implements CallbackHandler
class JAASMemoryLoginModule extends MemoryRealm implements LoginModule
class JAASRealm extends RealmBase
class JDBCRealm extends RealmBase
class JNDIRealm extends RealmBase
class LockOutRealm extends CombinedRealm
class MemoryRealm  extends RealmBase
class MemoryRuleSet extends RuleSetBase
class NullRealm extends RealmBase
abstract class RealmBase extends LifecycleMBeanBase implements Realm
class UserDatabaseRealm extends RealmBase
class X509SubjectDnRetriever implements X509UsernameRetriever
interface X509UsernameRetriever
interface Realm
interface Role extends Principal
class Constants
class DeployXmlPermission extends BasicPermission
 class SecurityClassLoad
 class SecurityConfig
class SecurityListener implements LifecycleListener
 class SecurityUtil
interface Server extends Lifecycle
interface Service extends Lifecycle
 class CGIServlet extends HttpServlet
class Constants
class DefaultServlet extends HttpServlet
class WebdavServlet extends DefaultServlet
class Constants
 class FileStore extends StoreBase
class JDBCStore extends StoreBase
abstract class ManagerBase extends LifecycleMBeanBase implements Manager
 class PersistentManager extends PersistentManagerBase
abstract class PersistentManagerBase extends ManagerBase implements DistributedManager
class StandardManager extends ManagerBase
class StandardSession implements HttpSession, Session, Serializable
class StandardSessionFacade implements HttpSession
abstract class StoreBase extends LifecycleBase implements Store
class TooManyActiveSessionsException extends IllegalStateException
interface Session
 class SessionEvent extends EventObject
interface SessionIdGenerator
interface SessionListener extends EventListener
class ByteArrayServletOutputStream extends ServletOutputStream
class ExpressionParseTree
class ExpressionTokenizer
class ResponseIncludeWrapper extends HttpServletResponseWrapper
interface SSICommand
class SSIConditional implements SSICommand
class SSIConditionalState
 class SSIConfig implements SSICommand
class SSIEcho implements SSICommand
class SSIExec implements SSICommand
interface SSIExternalResolver
class SSIFilter implements Filter
 class SSIFlastmod implements SSICommand
 class SSIFsize implements SSICommand
 class SSIInclude implements SSICommand
class SSIMediator
class SSIPrintenv implements SSICommand
class SSIProcessor
class SSIServlet extends HttpServlet
class SSIServletExternalResolver implements SSIExternalResolver
class SSIServletRequestUtil
class SSISet implements SSICommand
class SSIStopProcessingException extends Exception
 class Bootstrap
class Catalina
class CatalinaProperties
 class ClassLoaderFactory
class ConnectorCreateRule extends Rule
 class Constants
class ContextConfig implements LifecycleListener
class ContextRuleSet extends RuleSetBase
class CopyParentClassLoaderRule extends Rule
class DigesterFactory
class Embedded  extends StandardService
class EngineConfig implements LifecycleListener
class EngineRuleSet extends RuleSetBase
class ExpandWar
class FailedContext extends LifecycleMBeanBase implements Context
 class HomesUserDatabase implements UserDatabase
class HostConfig implements LifecycleListener
class HostRuleSet extends RuleSetBase
class LifecycleListenerRule extends Rule
class NamingRuleSet extends RuleSetBase
 class PasswdUserDatabase implements UserDatabase
class RealmRuleSet extends RuleSetBase
class SafeForkJoinWorkerThreadFactory implements ForkJoinWorkerThreadFactory
class SetAllPropertiesRule extends Rule
class SetContextPropertiesRule extends Rule
class SetNextNamingRule extends Rule
 class TldConfig  implements LifecycleListener
class TldRuleSet extends RuleSetBase
class Tomcat
 class Tool
 class UserConfig implements LifecycleListener
interface UserDatabase
class VersionLoggerListener implements LifecycleListener
class WebAnnotationSet
class WebappServiceLoader
class WebRuleSet extends RuleSetBase
class XmlErrorHandler implements ErrorHandler
interface Store
class ByteMessage implements Externalizable
interface Channel
class ChannelException extends Exception
interface ChannelInterceptor extends MembershipListener, Heartbeat
interface ChannelListener
interface ChannelMessage extends Serializable, Cloneable
interface ChannelReceiver extends Heartbeat
interface ChannelSender extends Heartbeat
 class Constants
interface ErrorHandler
class AbsoluteOrder
class ChannelCoordinator extends ChannelInterceptorBase implements MessageListener
abstract class ChannelInterceptorBase implements ChannelInterceptor
interface ExtendedRpcCallback extends RpcCallback
class GroupChannel extends ChannelInterceptorBase implements ManagedChannel
class InterceptorPayload
class DomainFilterInterceptor extends ChannelInterceptorBase
class FragmentationInterceptor extends ChannelInterceptorBase
class GzipInterceptor extends ChannelInterceptorBase
class MessageDispatch15Interceptor extends MessageDispatchInterceptor
class MessageDispatchInterceptor extends ChannelInterceptorBase implements Runnable
class NonBlockingCoordinator extends ChannelInterceptorBase
class OrderInterceptor extends ChannelInterceptorBase
class SimpleCoordinator extends ChannelInterceptorBase
class StaticMembershipInterceptor extends ChannelInterceptorBase
class TcpFailureDetector extends ChannelInterceptorBase
class TcpPingInterceptor extends ChannelInterceptorBase
class ThroughputInterceptor extends ChannelInterceptorBase
class TwoPhaseCommitInterceptor extends ChannelInterceptorBase
class Response
interface RpcCallback
class RpcChannel implements ChannelListener
class RpcMessage implements Externalizable
interface Heartbeat
class BufferPool
class BufferPool15Impl implements BufferPool.BufferPoolAPI
class ChannelData implements ChannelMessage
class DirectByteArrayOutputStream extends OutputStream
interface ListenCallback
class ObjectReader
 class ReplicationStream extends ObjectInputStream
class XByteBuffer
interface ManagedChannel extends Channel
interface Member
class Constants
class McastService implements MembershipService,MembershipListener,MessageListener
class McastServiceImpl
class MemberImpl implements Member, java.io.Externalizable
class Membership implements Cloneable
class StaticMember extends MemberImpl
interface MembershipListener
interface MembershipService
interface MessageListener

@enduml