@startuml


interface BeanFactory

interface SingletonBeanRegistry

interface AliasRegistry

interface ListableBeanFactory extends BeanFactory

interface HierarchicalBeanFactory extends BeanFactory

interface ConfigurableBeanFactory extends HierarchicalBeanFactory, SingletonBeanRegistry

interface AutowireCapableBeanFactory extends BeanFactory

class SimpleAliasRegistry implements AliasRegistry

interface BeanDefinitionRegistry extends AliasRegistry

class DefaultSingletonBeanRegistry extends SimpleAliasRegistry implements SingletonBeanRegistry

abstract class FactoryBeanRegistrySupport extends DefaultSingletonBeanRegistry

abstract class AbstractBeanFactory extends FactoryBeanRegistrySupport implements ConfigurableBeanFactory

abstract class AbstractAutowireCapableBeanFactory extends AbstractBeanFactory implements AutowireCapableBeanFactory

interface ConfigurableListableBeanFactory extends ListableBeanFactory, AutowireCapableBeanFactory, ConfigurableBeanFactory

class XmlBeanFactory extends DefaultListableBeanFactory

class DefaultListableBeanFactory extends AbstractAutowireCapableBeanFactory implements ConfigurableListableBeanFactory, BeanDefinitionRegistry, Serializable

@enduml