@startuml

interface InputStreamSource

interface Resource extends InputStreamSource

abstract class AbstractResource implements Resource

class InputStreamResource extends AbstractResource

abstract class AbstractFileResolvingResource extends AbstractResource

class BeanDefinitionResource extends AbstractResource

class DescriptiveResource extends AbstractResource

class FileSystemResource extends AbstractResource implements WritableResource

interface WritableResource extends Resource

class PathResource extends AbstractResource implements WritableResource

class ServletContextResource extends AbstractFileResolvingResource implements ContextResource

class VfsResource extends AbstractResource

class ClassPathResource extends AbstractFileResolvingResource

@enduml